### ISSUE TITLE
Do not require setting up UI and API urls

### ISSUE THREAD

**Issue by Suor** [iterative/studio-selfhosted#3]
Ideally should start a server, which handles both.

**Comment by omesser** [comment]
I think that one can be closed now

> > I don't think that the variables are actually required — they're localhost:3000 and localhost:8000 by default, so if they're not provided, it'll still kinda work, right?
> 
> That depends where you launch the service - for docker-compose and minikube localhost value is enough, but not for kubernetes in general, cause the customer needs to set up his own ingress for handling traffic to the cluster

for local/single node machine - looks like those to env vars are not required (above),
and for any k8s scenario (minikube included) - docker-compose is deprecated in favour of the new  helm chart: https://github.com/iterative/helm-charts/blob/main/charts/studio/values.yaml#L10
Which abstracts this away a little better, provide 1 hostname under `global.host`. However, in k8s there will be extra complexity to handle anyways - install ingress controller or another network access to the cluster
