### ISSUE TITLE
Setup ingresses in K8s version

### ISSUE THREAD

**Issue by natikgadzhi** [iterative/studio-selfhosted#5]
I'm not absolutely sure, but I think it's actually possible for both docker-compose and k8s. 

If we're allowing folks to setup hostnames via some vars (#3), it also makes sense to provision those hostnames and resolve them correctly.  

In case of K8s, we can throw in some ingress resources that should take care of that, without expressing an opinion on which ingress class (Traefik vs Nginx) they should use. 

In case of docker-compose, I think Docker can take care of hostnames for us, at least there's a `hostname:` param for a service, and we can describe the network and aliases for hosts, i.e. use default bridge network and set aliases that should resolve at least on the docker host. I don't know if docker-compose can actually provide ingresses — probably not, and it's probably obvious enough to the end users that they're responsible for routing traffic to the container if they prefer docker.

WDYT?

**Comment by jesper7** [comment]
Ingresses are now available with the Studio Helm chart: https://github.com/iterative/helm-charts
