### ISSUE TITLE
API_URL is added to UI_URL if no schema provided

### ISSUE THREAD

**Issue by nik123** [iterative/studio-selfhosted#7]
When I run `install.sh` without https/https part in `API_URL` variable, then `API_URL` is added to `BACKEND_URL` during authorization.

**Environment:**
1. Ubuntu 18.04.
2. docker-compose 1.28.2.
3. GitHub OAuth app.

**How to reproduce:**
1. Register your OAuth application on github according to instructions.
2. Login to private Iterative repository.
3. Run install script with command (IP address depends on your network configuration): `UI_URL=192.168.1.33:3000 API_URL=192.168.1.33:8000/api GITHUB_CLIENT_ID=<client-id> GITHUB_SECRET_KEY=<secret-key> ./install.sh`
4. Open `http://192.168.1.33:3000` in you browser.
5. Click log in button.

**Result:**
You will get 404 error and for a moment there will be the following address in address bar of your browser: `192.168.1.33:3000/192.168.1.33:8000/api/login/github`

**Expected behavior:**
Not sure, probably one of two options:
1. Do not allow `UI_URL`, `API_URL` without http/https part.
2. Somehow mention in the docs that if no http/https part provided, then `API_URL` is added to `UI_URL`.

**Comment by omesser** [comment]
This is abstracted away in our new supported installation method, using the studio helm chart (requires k8s). See: https://github.com/iterative/helm-charts
In the values structure, we take care of constructing the api/ui urls from given `global.host` to avoid host/url confusion
The docker-compose installation method is being phased out (still supported for existing customers until we reach out with a migration path).
